/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosRideSharingRouteImport } from './routes/scenarios/ride-sharing'
import { Route as ScenariosFlashSaleRouteImport } from './routes/scenarios/flash-sale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRideSharingRoute = ScenariosRideSharingRouteImport.update({
  id: '/scenarios/ride-sharing',
  path: '/scenarios/ride-sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosFlashSaleRoute = ScenariosFlashSaleRouteImport.update({
  id: '/scenarios/flash-sale',
  path: '/scenarios/flash-sale',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scenarios/flash-sale': typeof ScenariosFlashSaleRoute
  '/scenarios/ride-sharing': typeof ScenariosRideSharingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scenarios/flash-sale': typeof ScenariosFlashSaleRoute
  '/scenarios/ride-sharing': typeof ScenariosRideSharingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scenarios/flash-sale': typeof ScenariosFlashSaleRoute
  '/scenarios/ride-sharing': typeof ScenariosRideSharingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scenarios/flash-sale' | '/scenarios/ride-sharing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scenarios/flash-sale' | '/scenarios/ride-sharing'
  id: '__root__' | '/' | '/scenarios/flash-sale' | '/scenarios/ride-sharing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScenariosFlashSaleRoute: typeof ScenariosFlashSaleRoute
  ScenariosRideSharingRoute: typeof ScenariosRideSharingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/ride-sharing': {
      id: '/scenarios/ride-sharing'
      path: '/scenarios/ride-sharing'
      fullPath: '/scenarios/ride-sharing'
      preLoaderRoute: typeof ScenariosRideSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/flash-sale': {
      id: '/scenarios/flash-sale'
      path: '/scenarios/flash-sale'
      fullPath: '/scenarios/flash-sale'
      preLoaderRoute: typeof ScenariosFlashSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScenariosFlashSaleRoute: ScenariosFlashSaleRoute,
  ScenariosRideSharingRoute: ScenariosRideSharingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
